name = "league-tracker"
main = "src/index.js"
compatibility_date = "2024-01-01"

[env]
# D1 database binding
[[d1_databases]]
binding = "DB"
database_name = "league-tracker"
database_id = "ccf38d5e-1639-4eb3-8447-9f3644127e4b"

[triggers]
crons = ["15 20 * * 3", "15 21 * * 3", "0 7 * * 4"]

[vars]
ALLOWED_ORIGIN = "https://filippudak.github.io"

[observability.logs]
enabled = true
head_sampling_rate = 1
invocation_logs = true
persist = true

[observability.traces]
enabled = false
head_sampling_rate = 1
persist = true
