INSERT OR REPLACE INTO settings (key, value) VALUES ('ACTIVE_SEASON_ID', 'S6');
INSERT OR REPLACE INTO settings (key, value) VALUES ('CURRENT_WEEK', 'Season Ended');
INSERT OR REPLACE INTO settings (key, value) VALUES ('SEASON_LENGTH', '11');
INSERT OR REPLACE INTO settings (key, value) VALUES ('VOTING_OPEN', 'FALSE');
INSERT OR REPLACE INTO settings (key, value) VALUES ('TIMEZONE', 'Europe/Stockholm');
INSERT OR REPLACE INTO settings (key, value) VALUES ('WEEKLY_DEADLINE_DAY', 'Wednesday');
INSERT OR REPLACE INTO settings (key, value) VALUES ('WEEKLY_DEADLINE_TIME', '17:45');
INSERT OR REPLACE INTO settings (key, value) VALUES ('AUTO_ADVANCE_WEEK', 'TRUE');
INSERT OR REPLACE INTO players (id, name, melee_name, email, active) VALUES ('P001', 'Dennis Westberg', 'Deguwe', 'deguwe@gmail.com', 1);
INSERT OR REPLACE INTO players (id, name, melee_name, email, active) VALUES ('P002', 'Christoffer Wahlsten', 'CWahlsten', NULL, 1);
INSERT OR REPLACE INTO players (id, name, melee_name, email, active) VALUES ('P003', 'Filip Pudak', 'Anomandarix', 'filip.pudak@gmail.com', 1);
INSERT OR REPLACE INTO players (id, name, melee_name, email, active) VALUES ('P004', 'Zlikk', 'Zlikk', NULL, 1);
INSERT OR REPLACE INTO players (id, name, melee_name, email, active) VALUES ('P005', 'Tosse', 'Tosse', NULL, 1);
INSERT OR REPLACE INTO players (id, name, melee_name, email, active) VALUES ('P006', 'Emano', 'Emano', NULL, 1);
INSERT OR REPLACE INTO players (id, name, melee_name, email, active) VALUES ('P007', 'AlbinSWU', 'AlbinSWU', NULL, 1);
INSERT OR REPLACE INTO players (id, name, melee_name, email, active) VALUES ('P008', 'Alwin Bengtsson', 'Alwin_Bengtsson', NULL, 1);
INSERT OR REPLACE INTO players (id, name, melee_name, email, active) VALUES ('P009', 'Kaunisvaara', 'Kaunisvaara', NULL, 1);
INSERT OR REPLACE INTO players (id, name, melee_name, email, active) VALUES ('P010', 'Jonas Söderberg', 'KaprateKid', NULL, 1);
INSERT OR REPLACE INTO players (id, name, melee_name, email, active) VALUES ('P011', 'TomasT', 'TomasT', NULL, 1);
INSERT OR REPLACE INTO players (id, name, melee_name, email, active) VALUES ('P012', 'DavidSiv', 'DavidSiv', NULL, 1);
INSERT OR REPLACE INTO players (id, name, melee_name, email, active) VALUES ('P013', 'Niklas Lindroth', 'Fireskyfirst', NULL, 1);
INSERT OR REPLACE INTO players (id, name, melee_name, email, active) VALUES ('P014', 'lazycoin', 'lazycoin', NULL, 1);
INSERT OR REPLACE INTO players (id, name, melee_name, email, active) VALUES ('P015', 'johansanden', 'johansanden', NULL, 1);
INSERT OR REPLACE INTO players (id, name, melee_name, email, active) VALUES ('P016', 'edw1n', 'edw1n', NULL, 1);
INSERT OR REPLACE INTO players (id, name, melee_name, email, active) VALUES ('P017', 'timetogetnasty', 'timetogetnasty', 'timetogetnasty@gmail.com', 1);
INSERT OR REPLACE INTO players (id, name, melee_name, email, active) VALUES ('P018', 'il_voce', 'il_voce', NULL, 1);
INSERT OR REPLACE INTO players (id, name, melee_name, email, active) VALUES ('P019', 'Cassandor', 'Cassandor', NULL, 1);
INSERT OR REPLACE INTO players (id, name, melee_name, email, active) VALUES ('P020', 'ShabaZw', 'ShabaZw', 'vildan.strikovic@gmail.com', 1);
INSERT OR REPLACE INTO players (id, name, melee_name, email, active) VALUES ('P021', 'Kingrags', 'Kingrags', NULL, 1);
INSERT OR REPLACE INTO players (id, name, melee_name, email, active) VALUES ('P022', 'Sigge Maslov', '232ac9f5c14b4d19b83ffcfb9df3ed05', NULL, 1);
INSERT OR REPLACE INTO players (id, name, melee_name, email, active) VALUES ('P023', 'Robbo1981', 'Robbo1981', NULL, 1);
INSERT OR REPLACE INTO players (id, name, melee_name, email, active) VALUES ('P024', 'XOY959097', 'XOY959097', NULL, 1);
INSERT OR REPLACE INTO players (id, name, melee_name, email, active) VALUES ('P025', 'Björn Christiansen', 'Everlast', NULL, 1);
INSERT OR REPLACE INTO players (id, name, melee_name, email, active) VALUES ('P026', 'Viktor Edström', 'kjsd', NULL, 1);
INSERT OR REPLACE INTO players (id, name, melee_name, email, active) VALUES ('P027', 'TheAzrael2025', 'TheAzrael2025', NULL, 1);
INSERT OR REPLACE INTO players (id, name, melee_name, email, active) VALUES ('P028', 'henmas1981', 'henmas1981', NULL, 1);
INSERT OR REPLACE INTO players (id, name, melee_name, email, active) VALUES ('P029', 'Sparshong', 'Sparshong', NULL, 1);
INSERT OR REPLACE INTO players (id, name, melee_name, email, active) VALUES ('P030', 'striderheng', 'striderheng', NULL, 1);
INSERT OR REPLACE INTO players (id, name, melee_name, email, active) VALUES ('P031', 'Nikiva', 'Nikiva', NULL, 1);
INSERT OR REPLACE INTO players (id, name, melee_name, email, active) VALUES ('P032', 'GioDiena', 'GioDiena', NULL, 1);
INSERT OR REPLACE INTO players (id, name, melee_name, email, active) VALUES ('P033', 'mrtnflrn', 'mrtnflrn', NULL, 1);
INSERT OR REPLACE INTO players (id, name, melee_name, email, active) VALUES ('P034', 'TimAgge', 'TimAgge', NULL, 1);
INSERT OR REPLACE INTO players (id, name, melee_name, email, active) VALUES ('P035', 'Ade70', 'Ade70', NULL, 1);
INSERT OR REPLACE INTO players (id, name, melee_name, email, active) VALUES ('P036', 'MaxKonrad', 'MaxKonrad', NULL, 1);
INSERT OR REPLACE INTO players (id, name, melee_name, email, active) VALUES ('P037', 'DARTHRINDI', 'DARTHRINDI', NULL, 1);
INSERT OR REPLACE INTO players (id, name, melee_name, email, active) VALUES ('P038', 'darthlojo', 'darthlojo', NULL, 1);
INSERT OR REPLACE INTO players (id, name, melee_name, email, active) VALUES ('P039', 'MartinL', 'MartinL', NULL, 1);
INSERT OR REPLACE INTO players (id, name, melee_name, email, active) VALUES ('P040', 'Gfbe', 'Gfbe', NULL, 1);
INSERT OR REPLACE INTO players (id, name, melee_name, email, active) VALUES ('P041', 'bellacernaja', 'bellacernaja', NULL, 1);
INSERT OR REPLACE INTO players (id, name, melee_name, email, active) VALUES ('P042', 'Johan Nilsson', 'Scarecroww', NULL, 1);
INSERT OR REPLACE INTO players (id, name, melee_name, email, active) VALUES ('P043', 'Svenppamon123', 'Svenppamon123', NULL, 1);
INSERT OR REPLACE INTO leaders (id, name, "set", active) VALUES ('1', 'Admiral Ackbar', 'JTL', 1);
INSERT OR REPLACE INTO leaders (id, name, "set", active) VALUES ('2', 'Admiral Holdo', 'JTL', 1);
INSERT OR REPLACE INTO leaders (id, name, "set", active) VALUES ('3', 'Admiral Piett', 'JTL', 1);
INSERT OR REPLACE INTO leaders (id, name, "set", active) VALUES ('4', 'Admiral Trench', 'JTL', 1);
INSERT OR REPLACE INTO leaders (id, name, "set", active) VALUES ('5', 'Asajj Ventress', 'JTL', 1);
INSERT OR REPLACE INTO leaders (id, name, "set", active) VALUES ('6', 'Boba Fett', 'JTL', 1);
INSERT OR REPLACE INTO leaders (id, name, "set", active) VALUES ('7', 'Captain Phasma', 'JTL', 1);
INSERT OR REPLACE INTO leaders (id, name, "set", active) VALUES ('8', 'Darth Vader', 'JTL', 1);
INSERT OR REPLACE INTO leaders (id, name, "set", active) VALUES ('9', 'Grand Admiral Thrawn', 'JTL', 1);
INSERT OR REPLACE INTO leaders (id, name, "set", active) VALUES ('10', 'Han Solo', 'JTL', 1);
INSERT OR REPLACE INTO leaders (id, name, "set", active) VALUES ('11', 'Kazuda Xiono', 'JTL', 1);
INSERT OR REPLACE INTO leaders (id, name, "set", active) VALUES ('12', 'Lando Calrissian', 'JTL', 1);
INSERT OR REPLACE INTO leaders (id, name, "set", active) VALUES ('13', 'Luke Skywalker', 'JTL', 1);
INSERT OR REPLACE INTO leaders (id, name, "set", active) VALUES ('14', 'Major Vonreg', 'JTL', 1);
INSERT OR REPLACE INTO leaders (id, name, "set", active) VALUES ('15', 'Poe Dameron', 'JTL', 1);
INSERT OR REPLACE INTO leaders (id, name, "set", active) VALUES ('16', 'Rio Durant', 'JTL', 1);
INSERT OR REPLACE INTO leaders (id, name, "set", active) VALUES ('17', 'Rose Tico', 'JTL', 1);
INSERT OR REPLACE INTO leaders (id, name, "set", active) VALUES ('18', 'Wedge Antilles', 'JTL', 1);
INSERT OR REPLACE INTO leaders (id, name, "set", active) VALUES ('19', 'Ahsoka Tano', 'LOF', 1);
INSERT OR REPLACE INTO leaders (id, name, "set", active) VALUES ('20', 'Anakin Skywalker', 'LOF', 1);
INSERT OR REPLACE INTO leaders (id, name, "set", active) VALUES ('21', 'Avar Kriss', 'LOF', 1);
INSERT OR REPLACE INTO leaders (id, name, "set", active) VALUES ('22', 'Barriss Offee', 'LOF', 1);
INSERT OR REPLACE INTO leaders (id, name, "set", active) VALUES ('23', 'Cal Kestis', 'LOF', 1);
INSERT OR REPLACE INTO leaders (id, name, "set", active) VALUES ('24', 'Darth Maul', 'LOF', 1);
INSERT OR REPLACE INTO leaders (id, name, "set", active) VALUES ('25', 'Darth Revan', 'LOF', 1);
INSERT OR REPLACE INTO leaders (id, name, "set", active) VALUES ('26', 'Grand Inquisitor', 'LOF', 1);
INSERT OR REPLACE INTO leaders (id, name, "set", active) VALUES ('27', 'Kanan Jarrus', 'LOF', 1);
INSERT OR REPLACE INTO leaders (id, name, "set", active) VALUES ('28', 'Kit Fisto', 'LOF', 1);
INSERT OR REPLACE INTO leaders (id, name, "set", active) VALUES ('29', 'Kylo Ren', 'LOF', 1);
INSERT OR REPLACE INTO leaders (id, name, "set", active) VALUES ('30', 'Morgan Elsbeth', 'LOF', 1);
INSERT OR REPLACE INTO leaders (id, name, "set", active) VALUES ('31', 'Mother Talzin', 'LOF', 1);
INSERT OR REPLACE INTO leaders (id, name, "set", active) VALUES ('32', 'Obi-Wan Kenobi', 'LOF', 1);
INSERT OR REPLACE INTO leaders (id, name, "set", active) VALUES ('33', 'Qui-Gon Jinn', 'LOF', 1);
INSERT OR REPLACE INTO leaders (id, name, "set", active) VALUES ('34', 'Rey', 'LOF', 1);
INSERT OR REPLACE INTO leaders (id, name, "set", active) VALUES ('35', 'Supreme Leader Snoke', 'LOF', 1);
INSERT OR REPLACE INTO leaders (id, name, "set", active) VALUES ('36', 'Third Sister', 'LOF', 1);
INSERT OR REPLACE INTO leaders (id, name, "set", active) VALUES ('37', 'Bail Organa', 'SEC', 1);
INSERT OR REPLACE INTO leaders (id, name, "set", active) VALUES ('38', 'C-3PO', 'SEC', 1);
INSERT OR REPLACE INTO leaders (id, name, "set", active) VALUES ('39', 'Cassian Andor', 'SEC', 1);
INSERT OR REPLACE INTO leaders (id, name, "set", active) VALUES ('40', 'Chancellor Palpatine', 'SEC', 1);
INSERT OR REPLACE INTO leaders (id, name, "set", active) VALUES ('41', 'Colonel Yularen', 'SEC', 1);
INSERT OR REPLACE INTO leaders (id, name, "set", active) VALUES ('42', 'Dedra Meero', 'SEC', 1);
INSERT OR REPLACE INTO leaders (id, name, "set", active) VALUES ('43', 'DJ', 'SEC', 1);
INSERT OR REPLACE INTO leaders (id, name, "set", active) VALUES ('44', 'Dryden Vos', 'SEC', 1);
INSERT OR REPLACE INTO leaders (id, name, "set", active) VALUES ('45', 'Governor Pryce', 'SEC', 1);
INSERT OR REPLACE INTO leaders (id, name, "set", active) VALUES ('46', 'Jabba the Hutt', 'SEC', 1);
INSERT OR REPLACE INTO leaders (id, name, "set", active) VALUES ('47', 'Lama Su', 'SEC', 1);
INSERT OR REPLACE INTO leaders (id, name, "set", active) VALUES ('48', 'Leia Organa', 'SEC', 1);
INSERT OR REPLACE INTO leaders (id, name, "set", active) VALUES ('49', 'Luthen Rael', 'SEC', 1);
INSERT OR REPLACE INTO leaders (id, name, "set", active) VALUES ('50', 'Mon Mothma', 'SEC', 1);
INSERT OR REPLACE INTO leaders (id, name, "set", active) VALUES ('51', 'Padmé Amidala', 'SEC', 1);
INSERT OR REPLACE INTO leaders (id, name, "set", active) VALUES ('52', 'Sabé', 'SEC', 1);
INSERT OR REPLACE INTO leaders (id, name, "set", active) VALUES ('53', 'Satine Kryze', 'SEC', 1);
INSERT OR REPLACE INTO leaders (id, name, "set", active) VALUES ('54', 'Sly Moore', 'SEC', 1);
INSERT OR REPLACE INTO leaders (id, name, "set", active) VALUES ('55', 'Agent Kallus', 'LAW', 1);
INSERT OR REPLACE INTO leaders (id, name, "set", active) VALUES ('56', 'Aurra Sing', 'LAW', 1);
INSERT OR REPLACE INTO leaders (id, name, "set", active) VALUES ('57', 'Boba Fett', 'LAW', 1);
INSERT OR REPLACE INTO leaders (id, name, "set", active) VALUES ('58', 'Chewbacca', 'LAW', 1);
INSERT OR REPLACE INTO leaders (id, name, "set", active) VALUES ('59', 'Darth Vader', 'LAW', 1);
INSERT OR REPLACE INTO leaders (id, name, "set", active) VALUES ('60', 'Director Krennic', 'LAW', 1);
INSERT OR REPLACE INTO leaders (id, name, "set", active) VALUES ('61', 'Enfys Nest', 'LAW', 1);
INSERT OR REPLACE INTO leaders (id, name, "set", active) VALUES ('62', 'Han Solo', 'LAW', 1);
INSERT OR REPLACE INTO leaders (id, name, "set", active) VALUES ('63', 'Hera Syndulla', 'LAW', 1);
INSERT OR REPLACE INTO leaders (id, name, "set", active) VALUES ('64', 'Jabba the Hutt', 'LAW', 1);
INSERT OR REPLACE INTO leaders (id, name, "set", active) VALUES ('65', 'Jyn Erso', 'LAW', 1);
INSERT OR REPLACE INTO leaders (id, name, "set", active) VALUES ('66', 'Lando Calrissian', 'LAW', 1);
INSERT OR REPLACE INTO leaders (id, name, "set", active) VALUES ('67', 'Leia Organa', 'LAW', 1);
INSERT OR REPLACE INTO leaders (id, name, "set", active) VALUES ('68', 'Saw Gerrera', 'LAW', 1);
INSERT OR REPLACE INTO leaders (id, name, "set", active) VALUES ('69', 'Sebulba', 'LAW', 1);
INSERT OR REPLACE INTO leaders (id, name, "set", active) VALUES ('70', 'The Client', 'LAW', 1);
INSERT OR REPLACE INTO leaders (id, name, "set", active) VALUES ('71', 'Tobias Beckett', 'LAW', 1);
INSERT OR REPLACE INTO leaders (id, name, "set", active) VALUES ('72', 'Vel Sartha', 'LAW', 1);
INSERT OR REPLACE INTO leaders (id, name, "set", active) VALUES ('73', 'Ahsoka Tano', 'ASH', 1);
INSERT OR REPLACE INTO leaders (id, name, "set", active) VALUES ('74', 'Baylan Skoll', 'ASH', 1);
INSERT OR REPLACE INTO leaders (id, name, "set", active) VALUES ('75', 'Bo-Katan Kryze', 'ASH', 1);
INSERT OR REPLACE INTO leaders (id, name, "set", active) VALUES ('76', 'Cad Bane', 'ASH', 1);
INSERT OR REPLACE INTO leaders (id, name, "set", active) VALUES ('77', 'Emperor Palpatine', 'ASH', 1);
INSERT OR REPLACE INTO leaders (id, name, "set", active) VALUES ('78', 'Ezra Bridger', 'ASH', 1);
INSERT OR REPLACE INTO leaders (id, name, "set", active) VALUES ('79', 'Fennec Shand', 'ASH', 1);
INSERT OR REPLACE INTO leaders (id, name, "set", active) VALUES ('80', 'Grand Admiral Sloane', 'ASH', 1);
INSERT OR REPLACE INTO leaders (id, name, "set", active) VALUES ('81', 'Grand Admiral Thrawn', 'ASH', 1);
INSERT OR REPLACE INTO leaders (id, name, "set", active) VALUES ('82', 'Greef Karga', 'ASH', 1);
INSERT OR REPLACE INTO leaders (id, name, "set", active) VALUES ('83', 'Grogu', 'ASH', 1);
INSERT OR REPLACE INTO leaders (id, name, "set", active) VALUES ('84', 'Luke Skywalker', 'ASH', 1);
INSERT OR REPLACE INTO leaders (id, name, "set", active) VALUES ('85', 'Moff Gideon', 'ASH', 1);
INSERT OR REPLACE INTO leaders (id, name, "set", active) VALUES ('86', 'Sabine Wren', 'ASH', 1);
INSERT OR REPLACE INTO leaders (id, name, "set", active) VALUES ('87', 'Shin Hati', 'ASH', 1);
INSERT OR REPLACE INTO leaders (id, name, "set", active) VALUES ('88', 'The Armorer', 'ASH', 1);
INSERT OR REPLACE INTO leaders (id, name, "set", active) VALUES ('89', 'The Mandalorian', 'ASH', 1);
INSERT OR REPLACE INTO leaders (id, name, "set", active) VALUES ('90', 'Vane', 'ASH', 1);
INSERT OR REPLACE INTO seasons (id, name, created_date) VALUES (6, 'Season 6', '2026-06-03');
INSERT OR REPLACE INTO awards (season_id, award_name, player_id, score) VALUES (6, 'Galactic Ambassador', 'P004', 6);
INSERT OR REPLACE INTO awards (season_id, award_name, player_id, score) VALUES (6, 'Galactic Ambassador', 'P003', 6);
INSERT OR REPLACE INTO awards (season_id, award_name, player_id, score) VALUES (6, 'Galactic Ambassador', 'P010', 5);
INSERT OR REPLACE INTO awards (season_id, award_name, player_id, score) VALUES (6, 'Galactic Schemer', 'P001', 11);
INSERT OR REPLACE INTO awards (season_id, award_name, player_id, score) VALUES (6, 'Galactic Schemer', 'P004', 7);
INSERT OR REPLACE INTO awards (season_id, award_name, player_id, score) VALUES (6, 'Galactic Schemer', 'P011', 6);
INSERT OR REPLACE INTO awards (season_id, award_name, player_id, score) VALUES (6, 'Galactic Ruler', 'P001', 67);
INSERT OR REPLACE INTO awards (season_id, award_name, player_id, score) VALUES (6, 'Galactic Ruler', 'P002', 66);
INSERT OR REPLACE INTO awards (season_id, award_name, player_id, score) VALUES (6, 'Galactic Ruler', 'P003', 63);
INSERT OR REPLACE INTO awards (season_id, award_name, player_id, score) VALUES (6, 'A New Hope', 'P008', 6);
INSERT OR REPLACE INTO awards (season_id, award_name, player_id, score) VALUES (6, 'A New Hope', 'P011', 4);
INSERT OR REPLACE INTO awards (season_id, award_name, player_id, score) VALUES (6, 'A New Hope', 'P001', 3);
INSERT OR REPLACE INTO awards (season_id, award_name, player_id, score) VALUES (6, 'Bounty Hunter', 'P002', 8);
INSERT OR REPLACE INTO awards (season_id, award_name, player_id, score) VALUES (6, 'Bounty Hunter', 'P004', 4);
INSERT OR REPLACE INTO awards (season_id, award_name, player_id, score) VALUES (6, 'Bounty Hunter', 'P006', 4);
INSERT OR REPLACE INTO sessions (token, player_id, device_id, email, created, last_active) VALUES ('c78959be-b6b6-4511-922a-0f240984f988', 'P003', 'b5bbeb26-b4ce-4e07-a932-a2801dc18a17', 'filip.pudak@gmail.com', '2026-09-03', '2026-09-03');
INSERT OR REPLACE INTO sessions (token, player_id, device_id, email, created, last_active) VALUES ('fe8347de-b433-4069-be74-d97b1be12b68', 'P003', 'f691ba06-5a59-41b5-a6bc-e639020ab4b2', 'filip.pudak@gmail.com', '2026-09-03', '2026-09-03');
INSERT OR REPLACE INTO sessions (token, player_id, device_id, email, created, last_active) VALUES ('9cb3c450-75b3-4aa4-a5ed-f441796d6260', 'P001', '2d02cf10-04c7-407b-a4a3-78a31dba7b9a', 'deguwe@gmail.com', '2026-09-03', '2026-09-03');
INSERT OR REPLACE INTO sessions (token, player_id, device_id, email, created, last_active) VALUES ('975d42c8-81bc-4d22-829b-3903e3efae53', 'P017', '737cea9a-68a1-410d-99d7-728adb7b8e36', 'timetogetnasty@gmail.com', '2026-09-03', '2026-09-03');
INSERT OR REPLACE INTO sessions (token, player_id, device_id, email, created, last_active) VALUES ('792dede4-0654-469e-8c05-a5eefbeee8dd', 'P020', '8c4cfa24-a21e-4c3f-90c4-e097009c33a3', 'vildan.strikovic@gmail.com', '2026-09-03', '2026-09-03');
INSERT OR REPLACE INTO sessions (token, player_id, device_id, email, created, last_active) VALUES ('263d217c-1006-4fa9-852b-caa242095857', 'P020', '67d5b82c-7a74-4c16-9ef6-9751be22a7f3', 'vildan.strikovic@gmail.com', '2026-09-03', '2026-09-03');